# Build Workflow

name: Build with Gradle

on:
  pull_request:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Set up Temurin 17 JDK
        uses: actions/setup-java@master
        with:
          java-version: 17
          distribution: temurin

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/loom-cache
            **/prebundled-jars
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Chmod Gradle
        run: chmod +x ./gradlew
        
      - name: Build Uber Jar
        run: ./gradlew shadowJar

#        - name: Build
#        run: ./gradlew build --no-daemon
        
      - name: Artifacts
        uses: qualk/upload-artifact-as-is@master
        with:
          path: build/libs/*.jar

        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}